# Setup
title: "zhehua's blog"
url: "https://zhehuaf.github.io/"
baseurl:
description: '个人博客，分享操作系统、编程相关内容'

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: Asia/Shanghai
analytics:
  tracking_id: UA-53167467-11

collections:
  'blob':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
